server:
  port: 9800
spring:
  application:
    name: ln-gateway
  cloud:
    gateway:
      routes:
        - id: ln-consumer
          uri: lb://ln-consumer
          predicates:
            - Path=/ln-service/**
          filters:
            - StripPrefix=1
       # CORS跨越配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # 开发环境设置为*，生产环境设置为域名
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - OPTION
              - POST
              - DELETE
              - PUT
#  security:
#    oauth2:
#      client:
#        registration:
#          ln:
#            client-name: LN社区
#            client-id: test1
#            redirect-uri: http://127.0.0.1:9800/login/oauth2/code/test1
#            client-secret: test123456
#            scope:
#              - oidc
#              - profile
#              - email
#            authorization-grant-type: refresh_token,client_credentials,authorization_code
#            client-authentication-method: client_secret_basic
#        provider:
#          ln:
#            authorization-uri: http://127.0.0.1:9700/oauth2/authorize
#            token-uri: http://127.0.0.1:9700/oauth2/token
#            user-info-uri: http://127.0.0.1:9700/userinfo
#            jwk-set-uri: http://127.0.0.1:9700/oauth2/jwks
system:
  ignorePath:
